from enum import Enum

class POStatus(str,Enum):
    CREATED = "CREATED"
    APPROVED = "APPROVED"
    TNA_PENDING = "TNA_PENDING"
    FABRIC_BOOKED = "FABRIC_BOOKED"
    IN_PRODUCTION = "IN_PRODUCTION"
    INLINE_QC = "INLINE_QC"
    FINAL_QC = "FINAL_QC"
    READY_TO_SHIP = "READY_TO_SHIP"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
