from enum import Enum


class RFQSupplierStatus(str, Enum):

    MATCHED = "MATCHED"
    QUOTATION_PENDING = "QUOTATION_PENDING"
    QUOTATION_RECEIVED = "QUOTATION_RECEIVED"
    NEGOTIATION = "NEGOTIATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"