from enum import Enum


class TNAStatus(str, Enum):

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DELAYED = "DELAYED"
    HOLD = "HOLD"
    CANCELLED = "CANCELLED"


class TNAActivityType(str, Enum):

    # Current 9-step strict workflow
    FABRIC_BOOKING = "FABRIC_BOOKING"
    CUTTING = "CUTTING"
    STITCHING_STARTED = "STITCHING_STARTED"
    WASHING = "WASHING"
    DRYING = "DRYING"
    SAMPLE_TESTING = "SAMPLE_TESTING"
    APPROVED = "APPROVED"
    IRONING = "IRONING"
    PACKAGING = "PACKAGING"

    # Legacy values kept for backward compatibility
    FABRIC_APPROVAL = "FABRIC_APPROVAL"
    LAB_DIP_APPROVAL = "LAB_DIP_APPROVAL"
    TRIMS_APPROVAL = "TRIMS_APPROVAL"
    FIT_SAMPLE = "FIT_SAMPLE"
    PP_SAMPLE = "PP_SAMPLE"
    SIZE_SET_SAMPLE = "SIZE_SET_SAMPLE"
    CAD_MARKER = "CAD_MARKER"
    PILOT_RUN = "PILOT_RUN"
    CUTTING_START = "CUTTING_START"
    STITCHING_START = "STITCHING_START"
    INLINE_INSPECTION = "INLINE_INSPECTION"
    MIDLINE_INSPECTION = "MIDLINE_INSPECTION"
    FINISHING = "FINISHING"
    PACKING = "PACKING"
    FINAL_INSPECTION = "FINAL_INSPECTION"
    METAL_DETECTION = "METAL_DETECTION"
    QA_APPROVAL = "QA_APPROVAL"
    CARTON_READY = "CARTON_READY"
    SHIPMENT_BOOKING = "SHIPMENT_BOOKING"
    CONTAINER_LOADING = "CONTAINER_LOADING"
    DISPATCH = "DISPATCH"
    DELIVERY = "DELIVERY"


# Strict sequential workflow — order is enforced
TNA_WORKFLOW_ORDER = [
    TNAActivityType.FABRIC_BOOKING,
    TNAActivityType.CUTTING,
    TNAActivityType.STITCHING_STARTED,
    TNAActivityType.WASHING,
    TNAActivityType.DRYING,
    TNAActivityType.SAMPLE_TESTING,
    TNAActivityType.APPROVED,
    TNAActivityType.IRONING,
    TNAActivityType.PACKAGING,
]


class TNAPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"