from enum import Enum


class TNAStatus(str, Enum):

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DELAYED = "DELAYED"
    HOLD = "HOLD"
    CANCELLED = "CANCELLED"


class TNAActivityType(str, Enum):

    # PRE PRODUCTIOn
    FABRIC_BOOKING = "FABRIC_BOOKING"
    FABRIC_APPROVAL = "FABRIC_APPROVAL"
    LAB_DIP_APPROVAL = "LAB_DIP_APPROVAL"
    TRIMS_APPROVAL = "TRIMS_APPROVAL"
    FIT_SAMPLE = "FIT_SAMPLE"
    PP_SAMPLE = "PP_SAMPLE"
    SIZE_SET_SAMPLE = "SIZE_SET_SAMPLE"
    CAD_MARKER = "CAD_MARKER"
    PILOT_RUN = "PILOT_RUN"

    # PRODUCTION
    CUTTING_START = "CUTTING_START"
    STITCHING_START = "STITCHING_START"
    INLINE_INSPECTION = "INLINE_INSPECTION"
    MIDLINE_INSPECTION = "MIDLINE_INSPECTION"
    FINISHING = "FINISHING"
    PACKING = "PACKING"

    # QC
    FINAL_INSPECTION = "FINAL_INSPECTION"
    METAL_DETECTION = "METAL_DETECTION"
    QA_APPROVAL = "QA_APPROVAL"

    # SHIPPING
    CARTON_READY = "CARTON_READY"
    SHIPMENT_BOOKING = "SHIPMENT_BOOKING"
    CONTAINER_LOADING = "CONTAINER_LOADING"
    DISPATCH = "DISPATCH"
    DELIVERY = "DELIVERY"

    # USER-DEFINED
    CUSTOM = "CUSTOM"

class TNAPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"